---
version: "2"
use_cases:
- name: default
  sections:
  - name: Cycloid Worker
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Machine type"
        description: "Instance type for the worker."
        key: vm_machine_type
        widget: slider_list
        type: string
        default: "n2d-standard-2"
        values:
            - n1-standard-2
            - n2-standard-2
            - n2d-standard-2
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size for the instance."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 20
            - 250
        required: true

    - name: Cycloid core integration
      technologies: [pipeline]
      vars:
      - name: "Team ID"
        description: "This parameter can be obtained in Cycloid console, by clicking on your profile picture at the top right corner, then organization settings, then use the value of the ci_team_member field."
        key: team_id
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "Worker Private Key"
        description: "Leave default value if the worker is intended to run for the current organization. Otherwise, add Cycloid-worker-keys.ssh_prv credentials of the target organization."
        key: worker_key
        widget: cy_cred
        type: string
        default: "((cycloid-worker-keys.ssh_prv))"
        required: true

  - name: GCP Cloud Provider
    groups:
    - name: Where to deploy the new infrastructure
      technologies: [pipeline]
      vars:
      - name: "GCP project"
        description: "Google Cloud Platform project ID for Terraform."
        key: gcp_project
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "GCP region"
        description: "Google Cloud Platform region for new infrastructure."
        key: gcp_region
        widget: auto_complete
        type: string
        default: "europe-west1"
        values:
            - europe-west1
            - europe-west2
        required: true
      - name: "GCP zone"
        description: "Google Cloud Platform zone for new infrastructure."
        key: gcp_zone
        widget: auto_complete
        type: string
        default: "europe-west1-b"
        values:
            - europe-west1-b
            - europe-west1-c
            - europe-west1-d
            - europe-west2-a
            - europe-west2-b
            - europe-west2-c
        required: true      
      - name: "GCP credentials"
        description: "Google Cloud Platform JSON credentials to use for Terraform."
        key: gcp_credentials_json
        widget: cy_cred
        type: string
        default: "((gcp.json_key))"
        required: true